apiVersion: apps/v1
kind: Deployment
metadata:
  name: ljggy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ljggy
  template:
    metadata:
      labels:
        app: ljggy
    spec:
      containers:
      - image: okteto.dev/ljggy:latest
        name: ljggy
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "63e6b036-17c2-4731-8dea-540d193fee03"
        - name: Vless_Path
          value: "/v45ghf"
        - name: Vmess_UUID
          value: "f8bfb621-6728-4a6c-ae69-2106cd3d7c8a"
        - name: Vmess_Path
          value: "/vm666"
        - name: Share_Path
          value: "/v45ghf"
